title: Gruppo Bandistico Clesiano
description: Sito ufficiale del Gruppo Bandistico Clesiano
url: "https://gruppobandisticoclesiano.it"
baseurl: ""
lang: it
author: Fabio Molignoni
email: gruppobandisticoclesiano@gmail.com
theme_color: "#212031"
logo: /images/logo.png
default_image: /images/banda_home.webp

social:
  instagram: https://www.instagram.com/gruppobandisticoclesiano/
  facebook: https://www.facebook.com/gruppobandisticoclesiano
  youtube: https://www.youtube.com/channel/UCOmfaFXxRNBvoy282Y73JZw

address:
  street: Via Doss di Pez, 22
  postal_code: "38023"
  locality: Cles
  region: TN
  country: IT

defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: /images/banda_home.webp

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
